name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:HWUDvKf_SEuq1jpsEzxOFg@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:bY9qgNmnSGe37jUX0UDOcw/streams/AQAAADiloSEc6kJ4mxF90-KUv4gAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:nJTTloUkQ7aa3wv9lRUgEQ@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:bY9qgNmnSGe37jUX0UDOcw/streams/AQAAAC--1EHwfEzfrsqnOz3oyUEAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json
