name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:87AzTk70QciVVauaHkrCdQ@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:bY9qgNmnSGe37jUX0UDOcw/streams/AQAAAMVbGv94K0qcmXv1gQ8NWGkAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:e9WF3noLR1aR0FbQGHSWTw@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:bY9qgNmnSGe37jUX0UDOcw/streams/AQAAAAxOT9TTUUe2p8aLbKjMt-sAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json
